import Head from 'next/head'
import { BsFillMoonStarsFill, BsMedium} from 'react-icons/bs';
import {FaBloggerB} from 'react-icons/fa';
import {AiFillGithub,AiFillLinkedin,AiFillYoutube} from 'react-icons/ai';
import Image from 'next/image';

import design from '../public/design.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';

import ecom4 from '../public/ecom4.png';
import ecom5 from '../public/ecom5.png';


import profile from '../public/profile.png'
import {useState } from 'react';
import Link from 'next/link';


export default function Home() {
  const [darkmode,setDarkmode]= useState(false);
  return (
    <>
    <div className={darkmode ? 'dark':""}>
      <Head>
        <title>Balkrishna Pokharel Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className='min-h-screen'>
         
          <nav className='py-10 mb-12 flex justify-between dark:text-white'>
            <h1 className='text-xl font-burtons'>Balkrishna Pokharel</h1>
            <ul className='flex items-center'>
              <li className=' cursor-pointer text-2xl'><BsFillMoonStarsFill onClick={()=> setDarkmode(!darkmode)} /></li>
              <li>
                <a className=' bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8'   href="#">Resume</a></li>
            </ul>
          </nav>
          <div className=' text-center p-10 dark:text-white '>
            <h2 className=' text-5xl py-2 text-teal-600  font-medium md:text-6xl'>Balkrishna Pokharel</h2>
            <h3 className='text-2xl py-2 md:text-3xl'>React  Developer  || Node Developer</h3>
            <p className='text-md py-3 leading-8 text-gray-800 md:text-lg max-w- mx-auto dark:text-white'>CS & IT Students</p>

          </div>
          <div className='text-5xl flex justify-center gap-16 text-gray-600 dark:text-white'>
            <Link  href='https://github.com/krishbale' > <AiFillGithub />
            </Link>
         <Link href={"https://www.linkedin.com/in/balkrishna-pokharel-600a4814a/"} >          <AiFillLinkedin  />

         </Link>
          <Link  href='https://medium.com/@sushil.pokharel.7528'>
          <BsMedium />
          </Link>
         
        
          </div>
          <div className='relative mx-auto bg-gradient-to-t from-teal-500 rounded-full w-80 h-80 mt-10 overflow-hidden md:h-96 md:w-96 ' >
            <Image src={profile}  alt=''   />
          </div>
        </section>
        <section>
          <div className='dark:text-white'>
            <h3 className='text-3xl py-1 leading-8 text-gray-800 dark:text-white'>About me</h3>
                          <p> 
              MERN Stack Developer  with a total of 1 year of experience,
              proficient in designing and developing Web Application using  React as a Frontend Library 
              and  Node JS as a Backend Engine.
             
              </p>
              <p> Passionate and Hardworking person who is looking for a company with
              an open environment and a great culture where he can turn his
              knowledge into meaningful work while serving the company.
              
              </p><br />
            <p>With 4 years of knowledge in Bachlor Degree of CSIT &  Now looking for an internship/fresher job 
            
            to continuously learning about new web design trends makes him the beneficial and valuable for any company. </p>
          </div>
          <div className='lg:flex gap-10 dark:text-white'>
            <div className='text-center shadow-lg p-10 rounded-xl  my-10  '>
              <Image className='mx-auto'  src={design} width="100" height={100} alt=""/>
              <h3 className='text-lg font-medium pt-8 pb-2'>Designing</h3>
              <p className='py-2'>Replicating elegant design into beatiful UX/UI according to the  requirements specially using for web development</p>
              <h4 className='py-4 text-teal-600'>Familiar Design Tools </h4>
              <p className='text-gray-800 py-1 dark:text-white '>Figma</p>
              <p className='text-gray-800 py-1  dark:text-white '>Canava</p>
              <p className='text-gray-800 py-1  dark:text-white '>Illustrators</p>


            </div >
            <div className='text-center shadow-lg p-10 rounded-xl  my-10 '>
              <Image className='mx-auto'   src={code} width="100" height={100} alt=""/>
              <h3 className='text-lg font-medium pt-8 pb-2'>Coding</h3>
              <p className='py-2'> Clean  Coding   with responsive design and industry standard  </p>
              <h4 className='py-4 text-teal-600'>Main Coding Technology/Platform  </h4>
              <p className='text-gray-800 py-1  dark:text-white '>HTML ,CSS, JS, React, Bootstrap,Tail-Wind </p>
              <p className='text-gray-800 py-1  dark:text-white '>Node JS , Express JS , Prisma </p>
              <p className='text-gray-800 py-1  dark:text-white '>Mongo DB(Moongoose)   </p>


            </div>
            <div className='text-center shadow-lg p-10 rounded-xl  my-10'>
              <Image className='mx-auto'  src={consulting} width="100" height={100} alt=""/>
              <h3 className='text-lg font-medium pt-8 pb-2'>Testing & Deplyoment </h3>
              <p className='py-2'>Strong Debugging skills , and problems solving ideas and skills  </p>
              <h4 className='py-4 text-teal-600'>Testing and Optimization</h4>
              <p className='text-gray-800 py-1  dark:text-white '>Refactoring & Manual Testing </p>
              <p className='text-gray-800 py-1 dark:text-white'  >API Testing Using PostMan, </p>
              <p className='text-gray-800 py-1  dark:text-white '>Webpack </p>


            </div>
          </div>
        </section>
        <section>
          <div className='dark:text-white'>
            <h3 className='text-3xl py-1'>Porfolio</h3>
            <p className='dark:text-white'> Some of the project  snippets completed in <span className='text-teal-500'>Web Developement </span>are given below:-</p>
            <p>Nevertheless DemoLink are connected with image.</p>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
          
            <Link href={"https://nextflixdeploy-4hmt.vercel.app/auth"}>
            <p className='dark:text-white'>Full Stack Application Using Tailwind</p>
            <div className=' basis-1/3 flex-1 '><Image className=' rounded-lg object-cover w-100% h-100%' layout='responsive'  src={ecom4} alt="" /></div>
          
            </Link>
            <Link href={"https://gpt4deploy.vercel.app/"}>
            <p className='dark:text-white'>FrontEnd Static Applicaton using React component & Responsive CSS BEM </p>
            <div className=' basis-1/3 flex-1 '><Image className=' rounded-lg object-cover w-100% h-100%' layout='responsive'  src={ecom5} alt="" /></div>
          
            </Link>
            
         <p className='dark:text-white'> You can find the project details in  <Link href={"https://github.com/krishbale"}><span  className='text-teal-500'>Github.</span></Link></p>
            </div>
        </section>

      </main>
      </div>
    </>
  )
}
